sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t abanin/docker-react -f Dockerfile.dev .

script:
  - docker run abanin/docker-react npm run test -- --coverage